export enum ItemCategory {
  STOCK = 'STOCK',
  CRYPTO = 'CRYPTO',
  FOREX = 'FOREX',
  COMMODITY = 'COMMODITY',
  CAR = 'CAR',
  CLOTHING = 'CLOTHING',
  COLLECTABLE = 'COLLECTABLE',
  GENERAL = 'GENERAL',
}

export enum DataSource {
  ALPHA_VANTAGE = 'ALPHA_VANTAGE',
  COINGECKO = 'COINGECKO',
  FIXER = 'FIXER',
  EBAY_SCRAPE = 'EBAY_SCRAPE',
  STOCKX_SCRAPE = 'STOCKX_SCRAPE',
  NEWS_API = 'NEWS_API',
  NEWS_SCRAPE = 'NEWS_SCRAPE',
  OPENAI = 'OPENAI',
}
